Eui Badge
prysmex/ember-eui pull request #20
Opened 2020-10-21 00:48 UTC by SilvaMtz

2020-10-21 17:32 UTC, betocantu93 commented on addon/components/eui-badge/index.hbs
> +      href={{@href}}
I had the same issue before, where I had to choose between `<button />` and `<a />`, because I din't want to pass the href to a button I made this approach, but I don't know what you think? https://github.com/prysmex/ember-eui/blob/e654e3957cc9aa26a04ce1e959839e070ec965dd/addon/components/eui-side-nav-item/index.hbs#L21

2020-10-22 00:27 UTC, betocantu93 commented on addon/components/eui-badge/index.hbs
> +          <Element onClick={{@onClick}} href={{@href}} type="button" class={{if (or @onClick @href) "euiBadge__childButton" "euiBadge__text"}}>
Same here, I would like to know what happens if we set href to a span o.o?

2020-10-22 02:27 UTC, SilvaMtz commented on addon/components/eui-badge/index.hbs
> +      href={{@href}}
The thing is a bit more complicated that just not passing href to a button.
There are 3 cases that can apply in the badge:

1. The badge has no icon and has an href: the root element of the badge becomes an Anchor Element `<a>`.
2. The badge has no icon and has an onClick action: the root element of the badge becomes a button.
3. The badge has text and icon, and can have either onClick or href: The text (or icon) that has the onClick or href becomes a button or `<a>` and the root element of the badge becomes a span.

2020-10-22 02:29 UTC, SilvaMtz commented on addon/components/eui-badge/index.hbs
> +          <Element onClick={{@onClick}} href={{@href}} type="button" class={{if (or @onClick @href) "euiBadge__childButton" "euiBadge__text"}}>
As far as I'm concerned, setting the href to a span and not an anchor element, it may lead to some missing CSS styling applied specifically to `<a>` or `<button>`. We may need to test it.

2020-10-22 16:29 UTC, betocantu93 commented on addon/components/eui-badge/index.hbs
> +      href={{@href}}
Pretty much, yes, I abstracted the piece of repeating dom to a new template-only component to avoid repeating as much as possible, [`<EuiSideNavItem::Button />`](https://github.com/prysmex/ember-eui/blob/e654e3957cc9aa26a04ce1e959839e070ec965dd/addon/components/eui-side-nav-item/button/index.hbs) Doesn't really exists in the React implementation, because of how they can build components in JS,

2020-10-23 17:56 UTC, betocantu93 requested changes

2020-10-23 17:56 UTC, betocantu93 commented on tests/dummy/app/templates/demo/badge.hbs
> +      ----------------------------------------------------------
![image](https://user-images.githubusercontent.com/9092644/97037610-1e3ea400-152f-11eb-8276-493d42ed03d4.png)

2020-10-23 18:00 UTC, betocantu93 requested changes

2020-10-23 18:00 UTC, betocantu93 commented on addon/components/eui-badge/index.hbs
> +          <Element onClick={{@onClick}} href={{@href}} type="button" class={{if (or @onClick @href) "euiBadge__childButton" "euiBadge__text"}}>
We still need to do the if else here, right?

2020-10-23 20:24 UTC, SilvaMtz commented on tests/dummy/app/templates/demo/badge.hbs
> +      ----------------------------------------------------------
Watch the demo! 🤣

2020-10-23 20:38 UTC, SilvaMtz commented on addon/components/eui-badge/index.hbs
> +          <Element onClick={{@onClick}} href={{@href}} type="button" class={{if (or @onClick @href) "euiBadge__childButton" "euiBadge__text"}}>
Right. Forgot about that part lol. Its fixed now

2020-10-28 06:45 UTC, mtrunt requested changes

2020-10-28 06:45 UTC, mtrunt commented on types/global.d.ts
> +  inlineStyles(rest: Record<string, unknown>): string[];
Mark the `inlineStyles` property as optional (i.e. `inlineStyles?:...`) and if possible rename the `rest` parameter to something more related. Once this is optional the compiler should mark an error in cases like [this](https://github.com/prysmex/ember-eui/pull/20/files#diff-69ebc23a860e3feab22ab4121831a3fd184898e1b6aac2ebdbb7c48aca6541e8R10)

2020-10-28 16:30 UTC, betocantu93 requested changes

2020-10-28 16:30 UTC, betocantu93 commented on addon/helpers/inline-styles.ts
> +      assert(`Could not find component ${componentName} in cssMappings.`)
this could be simplified, the second argument to assert is a boolean, so if its false it will assert.

```ts
if(componentName){
  assert(`could not find component ${componentName} in cssMappings`, cssMappings[componentName as string]);
  styles.push(...cssMappings[componentName as string].inlineStyles(properties));
}

```

2020-10-28 18:20 UTC, SilvaMtz commented on addon/helpers/inline-styles.ts
> +      assert(`Could not find component ${componentName} in cssMappings.`)
Done!

2020-10-28 20:09 UTC, mtrunt requested changes

2020-10-28 20:09 UTC, mtrunt commented on addon/helpers/inline-styles.ts
> +export function inlineStyles(_:unknown, params:Record<string, unknown>) {
To avoid having to cast, create the interface and use it to type the `params` and remove the `as string` castings.
```suggestion
interface InlineStylesParams {
  componentName?: string;
  [property: string]: unknown;
}

export function inlineStyles(_: unknown, params: InlineStylesParams) {
```

2020-10-28 20:09 UTC, mtrunt commented on addon/helpers/inline-styles.ts
> +    styles.push(...cssMappings[componentName as string].inlineStyles?.(properties) as string[]);
Use non-null assertion to avoid casting

```suggestion
    styles.push(...cssMappings[componentName as string].inlineStyles!?.(properties));
```

2020-10-29 00:22 UTC, mtrunt approved these changes

2020-10-29 00:23 UTC, merged