Eui Card
prysmex/ember-eui pull request #22
Opened 2020-10-23 02:42 UTC by SilvaMtz

2020-10-23 06:28 UTC, mtrunt requested changes

2020-10-23 06:28 UTC, mtrunt commented on addon/modifiers/simulate-click.js
> +      element.removeEventListener("click", _targetClick)
Use single quotes in `js` files

2020-10-23 06:28 UTC, mtrunt commented on tests/dummy/app/controllers/demo/card.js
> +		console.log("You punched it into hyperspace!!");
Something more visible than a `console.log` should be used for the demo. Can be an alert, on-screen message, or anything the user can notice.
Use single quotes in `js` files.

2020-10-23 06:28 UTC, mtrunt commented on tests/dummy/app/controllers/demo/badge.js
> +		console.log("BADGE TEXT clicked!")
Something more visible than a `console.log` should be used for the demo. Can be an alert, on-screen message, or anything the user can notice.
Use single quotes in `js` files.

2020-10-23 16:47 UTC, betocantu93 requested changes

2020-10-23 16:47 UTC, betocantu93 commented on addon/modifiers/simulate-click.js
> +  function _targetClick (target) {
I would really make this more generic in three ways, 

1. Support any kind of event on the element to trigger the forwarding or simulation on the target
2. Support "forwarding" or "simulating" any kind of event to the target
3. Don't concatenate the `#`, let the client pass the whole selector or even another Element

2020-11-03 19:54 UTC, mtrunt requested changes

2020-11-03 19:54 UTC, mtrunt commented on addon/components/eui-card/eui-card-select/index.hbs
> +  onClick={{@onClick}}
Shouldn't these be passed with `@`?

2020-11-03 19:54 UTC, mtrunt commented on addon/modifiers/simulate-event.js
> +  let _target = element.querySelector(targetElement);
Can this be refactored to use the [Event API](https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events#Creating_custom_events)?

i.e. instead of relying on the element properties to get the handlers, create the event and use `dispatchEvent` to send the event.

2020-11-04 17:53 UTC, SilvaMtz commented on addon/components/eui-card/eui-card-select/index.hbs
> +  onClick={{@onClick}}
No, when it comes to EUI Buttons, the `type` refers to the HTML attribute, as well as the `onClick` action. Notice the EuiButtonEmpty does not have an `@onClick` prop. the onClick is passed directly with `...attributes`

2020-11-11 17:44 UTC, mtrunt approved these changes

2020-11-11 17:52 UTC, mtrunt approved these changes

2020-11-11 17:52 UTC, merged