Eui icon
prysmex/ember-eui pull request #3
Opened 2020-09-29 05:06 UTC by betocantu93

2020-09-29 22:20 UTC, mtrunt requested changes

2020-09-29 22:20 UTC, mtrunt commented on addon/components/common.ts
> +}
I think `className` should be omitted to make it more `Ember`-like. If you need to pass the class you add it with the `class` attribute.

2020-09-29 22:20 UTC, mtrunt commented on addon/components/eui-icon/index.ts
> +  }
The preferred use for this should be with the `class-names` helper.

2020-09-29 22:20 UTC, mtrunt commented on ember-cli-build.js
> +      ],
Inconsistent quotes (double, single)

2020-09-29 22:20 UTC, mtrunt commented on types/global.d.ts
> +  [size: string]: string | null;
What's the use case for allowing `null` values here?

2020-10-03 15:22 UTC, betocantu93 commented on addon/components/common.ts
> +}
The problem I'm facing is that I'm using [ember-svg-jar](https://github.com/ivanvotti/ember-svg-jar) addon, which gives us a helper which sets the passed arguments to the resulting svg element `{{svg-jar "something.svg" hola=10}}` but I unfortunately can't pass `...arguments` to a helper `{{svg-jar "something.svg" ...arguments}}` that's why I had to strictly pass className 😢  would be great if we can somehow handpick the class from these arguments....

Pseudocode: 
```hsb
{{#let (pick "class" arguments) as |class|}}
  {{svg-jar "something.svg" class=class}}
{{/let}}
```

2020-10-03 15:51 UTC, betocantu93 commented on addon/components/eui-icon/index.ts
> +  }
100% Agree!

2020-10-03 15:52 UTC, betocantu93 commented on types/global.d.ts
> +  [size: string]: string | null;
Eui Icon actually have it in their css mappings

https://github.com/prysmex/ember-eui/blob/2a876fc2f7fd9554108ec98dfd19798ed3db99a1/addon/utils/css-mappings/eui-icon.ts#L13

2020-10-03 23:49 UTC, mtrunt commented on types/global.d.ts
> +  [size: string]: string | null;
Instead of allowing `null` values, the `default` should be the empty string since it will evaluate to the same thing without widening the types.

`default` key can also be removed from the mappings and it would produce the same results.

2020-10-03 23:59 UTC, mtrunt commented
This may be outdated but the recommended use of quotes is single for JS/TS files and double for HTML/Templates.
I think the Prettier configuration is changing everything to single as it is.

2020-10-04 03:51 UTC, betocantu93 commented
> This may be outdated but the recommended use of quotes is single for JS/TS files and double for HTML/Templates.
> I think the Prettier configuration is changing everything to single as it is.

Yes, single quotes are for Js/ts and in handlebars the helpers arguments AFAIK, double quotes are for all other html strings like class, etc

2020-10-06 07:32 UTC, mtrunt requested changes
Looks good, only some suggestions. The `EuiAccordion` related files should be removed to keep this PR focused on `EuiIcon`.

2020-10-06 07:32 UTC, mtrunt commented on addon/components/eui-accordion/index.hbs
> +</div>
Remove from PR

2020-10-06 07:32 UTC, mtrunt commented on addon/components/eui-accordion/index.ts
> +}
Remove from PR

2020-10-06 07:32 UTC, mtrunt commented on addon/components/eui-icon/index.ts
> +};
This map could be moved to utils with the other components' maps

2020-10-06 07:32 UTC, mtrunt commented on addon/components/eui-icon/index.ts
> +      (/.+App$/.test(type) || /.+Job$/.test(type) || type === 'dataVisualizer')
This could be rewritten to `const appOrJobRE = new RegExp('.+(App|Job)$')` or `const appOrJobRE = /.+(App|Job)$/` and then just test on that inside the `if` to make it clearer IMO.

2020-10-06 07:32 UTC, mtrunt commented on addon/helpers/arg-or-default.ts
>  export default helper(argOrDefault);
Remove from PR

2020-10-06 07:32 UTC, mtrunt commented on addon/helpers/class-names.ts
>    classes.push(cssMappings[componentName].properties.size?.[size] || '');
Remove from PR

2020-10-06 07:32 UTC, mtrunt commented on addon/helpers/unique-id.ts
Remove from PR

2020-10-06 07:32 UTC, mtrunt commented on addon/utils/css-mappings/eui-accordion.ts
> +export default mapping;
Remove from PR

2020-10-13 00:43 UTC, merged