EuiPage
prysmex/ember-eui pull request #4
Opened 2020-09-29 23:09 UTC by SilvaMtz

# Description and Markup
This PR intends to implement the template-only component of Eui Page including the Eui Panel.

TODOS:
- restrictWidth Props in EuiPage and EuiPageContent
- EuiBetaBadge Component for EuiPanel

Example of markup is as follows (ignore the inline styling):
```hbs
<EuiPage style="height: 100%" as |Page|>
  {{! Page sidebar}}
  <Page.sidebar>
    Lorem ipsum
  </Page.sidebar>

  {{! Page body}}
  <Page.body as |Body|>

    {{!Page body header}}

    <Body.header as |Header|>
      <Header.section>
        <h1 style="font-size: 40px;">Lorem Ipsum</h1>
      </Header.section>
      <Header.section>
        Lorem Ipsum
      </Header.section>
    </Body.header>

    <Body.content @grow={{false}} @paddingSize="l" as |Content|>
      <Content.header as |Header|>
        <Header.section>
          Lorem Ipsum
        </Header.section>
        <Header.section>
          Lorem ipsum
        </Header.section>
      </Content.header>
      <Content.body>
        <p style="line-height: 2rem;">
          Lorem Ipsum
        </p>
      </Content.body>
    </Body.content>

  </Page.body>
</EuiPage>
```

# Screenshot
The example above can render you a layout like this:

![Screen Shot 2020-09-29 at 6 08 44 PM](https://user-images.githubusercontent.com/17131846/94625626-d2c20e80-027e-11eb-8da9-1431b4de6e2c.png)

2020-10-06 19:17 UTC, mtrunt requested changes

2020-10-06 19:17 UTC, mtrunt commented on addon/components/eui-page/eui-page-body/eui-page-content/index.hbs
> +  }}
Can the `class-names` helper be used here?

2020-10-06 19:17 UTC, mtrunt commented on addon/helpers/class-names.ts
>    classes.push(cssMappings[componentName].properties.size?.[size] || '');
Remove file from PR

2020-10-06 19:17 UTC, mtrunt commented on addon/utils/css-mappings/eui-panel.ts
> +  none: ``,
This is fine but can also be removed if it's the empty string.

2020-10-14 02:45 UTC, betocantu93 approved these changes

2020-10-14 02:45 UTC, merged